### ISSUE TITLE
Is LTI13Authenticator specific to IllumiDesk?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ltiauthenticator#101]
I lack a lot of background to understand this project as I've never used LTI1.1 or LTI1.3 for authentication, but I saw the following and become a bit concerned.

https://github.com/jupyterhub/ltiauthenticator/blob/2dd3549b41480b61225e2a07337bec26385a2432/ltiauthenticator/lti13/handlers.py#L52-L53

Is there anyone besides IllumiDesk using the LTI1.3 authenticator? @yuvipanda perhaps?

I'm not confident what it means that the LTI13ConfigHandler serving responses for `/lti13/config` respons with json including a title and description associated with IllumiDesk hardcoded by default.

**Comment by yuvipanda** [comment]
It is definitely used by people other than Illumidesk! They just graciously upstreamed their implementation, and those values probably just need to be moved into configurable traitlets

**Comment by yuvipanda** [comment]
I think LTIAuthenticator 1.3 might not be used by many at the moment because it has not been part of a z2jh release!

**Comment by yuvipanda** [comment]
If anything, this is my fault for not catching the hardcoded name during the upstreaming process. Sorry about that.
