### ISSUE TITLE
2FA required - jgwerner temporarily removed as a maintainer

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ltiauthenticator#108]
As part of https://github.com/jupyterhub/team-compass/issues/443, I've now removed access for @jgwerner by enabling a policy that enforces 2FA across the JupyterHub orgs' projects.

@jgwerner please let me know if you enable 2FA so I can grant you access again as a maintainer of this repo.

**Comment by jgwerner** [comment]
@consideRatio done!

**Comment by consideRatio** [comment]
@jgwerner nice! I've sent an invite for you again!
