### ISSUE TITLE
New user logins not effective when old user is logged in

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/ltiauthenticator#11]
If user A is already logged in, and a new LTI request authorizing user B comes in, JupyterHub should log out user A and log in user B. Currently, this doesn't seem to be happening, causing lots of confusion among users.

**Comment by sideye** [comment]
Currently it appears that user B will be automatically redirected to user A if user A was previously logged in.

**Comment by consideRatio** [comment]
Can this be, because `get_next_url` is called without passing the user object after logging in? In #26 I start doing that.

**Comment by consideRatio** [comment]
Is this a JupyterHub bug or a bug with this authenticator?

**Comment by consideRatio** [comment]
Resolved by #31.
