### ISSUE TITLE
401 : Unauthorized oauth_consumer_key not known

### ISSUE THREAD

**Issue by roblhibbard** [jupyterhub/ltiauthenticator#12]
401 : Unauthorized
oauth_consumer_key not known This is the error code, when I try to connect Jupyterhub to open edx platform.

this is my jupyter config:
<pre>
import os
c = get_config()
c.JupyterHub.log_level = 10
c.Spawner.cmd = '/home/robert/anaconda3/bin/jupyterhub-singleuser'

# Cookie Secret Files
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.ConfigurableHTTPProxy.auth_token = '/srv/jupyterhub/proxy_auth_token'

c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers = {
    os.environ['LTI_CLIENT_KEY']: os.environ['LTI_CLIENT_SECRET']
}

c.LocalGitHubOAuthenticator.create_system_users = True
c.Authenticator.whitelist = {'robert'}
c.Authenticator.admin_users = {'robert'}
</pre>

this is my nginx config:
<pre>
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
        worker_connections 1024;
        # multi_accept on;
}

http {
        include /etc/nginx/mime.types;

        default_type application/octet-stream;

    #top-level http config for websocket headers
        map $http_upgrade $connection_upgrade {
        default upgrade;
            ''      close;
    }

    # All regular http requests on port 80 become SSL/HTTPS requests on port 32
    server {
        listen 80;
        server_name jhub.hibbardsclass.org;

        # Tell all requests to port 80 to be 302 redirected to HTTPS
        return 302 https://$host$request_uri;
    }

    server {
 #listen 443 ssl default_server;
        listen 443;
        ssl on;
        server_name jhub.hibbardsclass.org;

        ## SSL Protocals
        ssl_certificate /etc/letsencrypt/live/jhub.hibbardsclass.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/jhub.hibbardsclass.org/privkey.pem;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /srv/jupyterhub/dhparam.pem;

        # Make site accessible from http://localhost/
        #server_name localhost;

        # certs sent to the client in SERVER HELLO are concatenated in
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;

        # modern configuration. tweak to your needs.
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1$

        # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
        add_header Strict-Transport-Security max-age=15768000;
       location /jupterhub {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;

            #proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location ~ /.well-known {
            allow all;
        }
    }
}
</pre>

I am running the juypterhub on Ubuntu 18.04 server. Keys are stored as env variables.

 LTI Passport String is setup in platform with this format

your-hub-name:client-key:client-secret.

any thoughts or ideas.

**Comment by consideRatio** [comment]
@roblhibbard I don't know myself =/ But, I've learned from inspecting the source code that this is an error coming from a validation of a request sent to /lti/launch, and that this webrequest to /lti/launch isn't passed the body argument in the POST request that represent consumer_key.

## Where the error comes from
https://github.com/jupyterhub/ltiauthenticator/blob/1f94f4290e08a84f391f401ea9d3fb7152ca3308/ltiauthenticator/__init__.py#L25-L46

## Why it gave you an error
https://github.com/jupyterhub/ltiauthenticator/blob/1f94f4290e08a84f391f401ea9d3fb7152ca3308/ltiauthenticator/__init__.py#L130-L149

**Comment by kiril-chilingarashvili** [comment]
I had similar problem with helm config
This is what worked 
![image](https://user-images.githubusercontent.com/10229823/144582916-e4efe9de-4789-4738-919b-9e424e7acd17.png)

**Comment by brospars** [comment]
I don't know if this is related but this was due to a copy/paste from the readme with an error `Line 107` it's written `LTI11Authenticator` instead of `LTIAuthenticator`, see :
https://github.com/jupyterhub/ltiauthenticator/blob/40a36c40fadfc3322f09eac7dfe7bc591b69778e/README.md#L105-L110
