### ISSUE TITLE
Multiple consistent authentication mechanisms?

### ISSUE THREAD

**Issue by dirkcgrunwald** [jupyterhub/ltiauthenticator#13]
We're using JupyterHub with OAUTH using out GSuite authentication to our university unique identifier mechanism. This is the same authentication ID that would be used if we used the LTI authenticator.

It would be nice to be able to use the LTI authenticator AND the OAUTH -- the use of the LTI would allow us to auto-create accounts for students by having them come in from LTI and then we could use the OAUTH mechanism if they want to directly access their instance rather than going in through the LMS (moodle, in our case).

Any idea if this is possible? The README indicates "no", but I'm curious how hard it would be to add. We're doing something similar for an autograder (https://inginious.org/)

**Comment by consideRatio** [comment]
I believe this is limited by JupyterHub not being configurable for use with multiple authenticators. =/

I'll close this in favor of https://github.com/jupyterhub/oauthenticator/issues/136 unless it makes sense to start discussion separately in this repo as well.
