### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by kaseyhackspace** [jupyterhub/ltiauthenticator#17]
Good day, I've always wanted to be a contributor to an open source project. While I was trying the authenticator out, I experienced a bug that I patched on my local server. I'd like to patch it up here and also contribute to the documentation if possible :).

**Comment by yuvipanda** [comment]
Awesome, @kaseyhackspace! Welcome <3

In this case, since you've already locally patched it, I'd say the next step is to open a Pull Request here with the description of the problem you encountered and your fix. How does that sound?

**Comment by kaseyhackspace** [comment]
That sounds awesome @yuvipanda ! Only problem is I don't think I'm authorised  to push my local branch. Tried to push it upstream but got a permission denied:

``` bash 
$ git push --set-upstream origin x-forwarded-proto-patch
remote: Permission to jupyterhub/ltiauthenticator.git denied to kaseyhackspace.
fatal: unable to access 'https://github.com/jupyterhub/ltiauthenticator/': The requested URL returned error: 403
```

**Comment by consideRatio** [comment]
@kaseyhackspace welcome! :heart:

You are not allowed to directly push to this code, before we change the code in this repository, we want to review and test it. If you create a GitHub Fork of this project, and push to that fork, you can then open a Pull Request which is like "a suggestion of a change" that can be reviewed and discussed before we change the code here.

:heart: for your work to help out!
