### ISSUE TITLE
Incompatibilities and hanging tljh-config reload

### ISSUE THREAD

**Issue by wmunters** [jupyterhub/ltiauthenticator#19]
I have been trying to get LTI authentification on a TLJH server hosted on Google Cloud (trying to incorporate Jupyter Notebooks in a course on Canvas). I'm following the description in http://tljh.jupyter.org/en/latest/install/google.html which all works fine.

However, when trying to use the LTI authentication as shown here, I run into problems. 
1. The latest jupyterhub release 1.0.0 require oauth 3.0, whereas lti authenticator here requires oauth 2.x
2. Upon configuring the LTI authentication method, the command sudo tljh-config reload hangs. Upon investigating the source code, I'm assuming this is because the jupyterhub server isn't coming back up again. 

Has anyone experienced any similar problems recently?

**Comment by tee-tan** [comment]
I also found the similar problem after deployed on private server, the `reload` and `reload hub` do not work (`reload proxy` works though).

I Installed following the doc
```
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin <admin-user-name>
```

The result..
```
hadoop@big-data-bi:~$ sudo tljh-config reload
active

(... hang up until I hit ctrl+c ...)

^CTraceback (most recent call last):
  File "/usr/bin/tljh-config", line 11, in <module>
    load_entry_point('the-littlest-jupyterhub==0.1', 'console_scripts', 'tljh-config')()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/config.py", line 398, in main
    reload_component(args.component)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/config.py", line 263, in reload_component
    time.sleep(1)
KeyboardInterrupt
```

**Comment by tee-tan** [comment]
I also found the similar problem after deployed on private server, the `reload` and `reload hub` do not work (`reload proxy` works though).

I Installed following the doc
```
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo -E python3 - --admin <admin-user-name>
```

The result..
```
XXXX@YYYYY:~$ sudo tljh-config reload
active

(... hang up until I hit ctrl+c ...)

^CTraceback (most recent call last):
  File "/usr/bin/tljh-config", line 11, in <module>
    load_entry_point('the-littlest-jupyterhub==0.1', 'console_scripts', 'tljh-config')()
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/config.py", line 398, in main
    reload_component(args.component)
  File "/opt/tljh/hub/lib/python3.6/site-packages/tljh/config.py", line 263, in reload_component
    time.sleep(1)
KeyboardInterrupt
```

**Comment by tee-tan** [comment]
I need to move my server so installed TLJH on another one but there's no issue :confused:

**Comment by jovincroninwilesmith** [comment]
@tee-tan I am experiencing the same issue. Were you able to find a solution?

**Comment by consideRatio** [comment]
I think these are symptoms of incompatible dependency requirements of JupyterHub and this authenticator. I've made some changes to make this authenticator support the newer upstream changes in `oauthlib` that a modern version of JupyterHub require. See #24.
