### ISSUE TITLE
Installation fails due to conflicting oauthlib version

### ISSUE THREAD

**Issue by NeolithEra** [jupyterhub/ltiauthenticator#21]
Hi, users are unable to run ltiauthenticator due to dependency conflict with _**oauthlib**_ package. 
As shown in the following full dependency graph of **_ltiauthenticator_**, **_ltiauthenticator_** requires _**oauthlib==2.***_，while **_jupyterhub_** requires _**oauthlib>=3.0**_.

According to pip’s _“first found wins”_ installation strategy, _**oauthlib==2.1.0**_ is the actually installed version. 
However, _**oauthlib==2.1.0**_ does not satisfy _**oauthlib>=3.0**_.

### Dependency tree
```
ltiauthenticator-0.3
| +-jupyterhub(version range:>=0.8)
| | +-alembic(version range:*)
| | | +-mako(version range:*)
| | | +-python-dateutil(version range:*)
| | | | +-six(version range:>=1.5)
| | | +-python-editor(version range:>=0.3)
| | | +-sqlalchemy(version range:>=0.9.0)
| | +-async-generator(version range:>=1.8)
| | +-certipy(version range:>=0.1.2)
| | +-entrypoints(version range:*)
| | +-jinja2(version range:*)
| | | +-markupsafe(version range:>=0.23)
| | +-oauthlib(version range:>=3.0)
| | +-pamela(version range:*)
| | +-prometheus-client(version range:>=0.0.21)
| | +-python-dateutil(version range:*)
| | | +-six(version range:>=1.5)
| | +-requests(version range:*)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:<1.26,>=1.21.1)
| | +-sqlalchemy(version range:>=1.1)
| | +-tornado(version range:>=5.0)
| | +-traitlets(version range:>=4.3.2)
| +-oauthlib(version range:==2.)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_oauthlib>=3.0_**. 

2.	Fix your direct dependency to be **_jupyterhub==0.8_**. 

3.	Remove your direct dependency oauthlib, and use oauthlib transitively introduced by jupyterhub.

I have checked these revisions will not affect your downstream projects now.
Which solution do you prefer, 1, 2 or 3?
@samhinshaw  Please let me know your choice. I can submit a PR to solve this issue.

**Comment by brospars** [comment]
Any update on this issue ?

From the [changelog](https://github.com/oauthlib/oauthlib/blob/master/CHANGELOG.rst#300-2019-01-01), I don't think oauthlib 3.0 would be a problem for `ltiauthenticator`.  
I'm in favor of relying on jupyterhub instead of a direct dependency, since it's a key feature of jupyterhub to be a oauth provider.

**Comment by yuvipanda** [comment]
This should be fixed by https://github.com/jupyterhub/ltiauthenticator/pull/23
