### ISSUE TITLE
AttributeError: 'LTIAuthenticator' object has no attribute 'request'

### ISSUE THREAD

**Issue by owen198** [jupyterhub/ltiauthenticator#22]
I am trying to integrate Jupyterhub and Moodle by using LTI

I generated **Key** and **Secret** by using command `openssl rand -hex 32`
Then I input **Key** and **Secret** into Moodle external tools, the following is the configuration:
```
Tool name: Jupyterhub
Tool URL: http:///MY_HOST/hub/lti/launch
Key: generated by openssl
Secret: generated by openssl
```

And the following is my `jupyterhub_config.py`
```
c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers = {
        "Key": "Secret"
}
```

Finally, I add configured external tool into the course and add the URL on the course dashboard, however, once I clicked the URL, I got following error message:
```
[W 2019-08-31 09:44:00.599 JupyterHub log:174] 405 GET /hub/lti/launch (@172.24.0.1) 38.61ms
[E 2019-08-31 09:44:07.155 JupyterHub web:1788] Uncaught exception POST /hub/lti/launch (180.217.109.173)
    HTTPServerRequest(protocol='http', host='MY_JUPYTER_HOST', method='POST', uri='/hub/lti/launch', version='HTTP/1.1', remote_ip='180.217.109.173')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/conda/lib/python3.6/site-packages/ltiauthenticator/__init__.py", line 187, in post
        user = yield self.login_user()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 655, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/conda/lib/python3.6/site-packages/ltiauthenticator/__init__.py", line 141, in authenticate
        protocol = self.request.protocol
    AttributeError: 'LTIAuthenticator' object has no attribute 'request'
    
[E 2019-08-31 09:44:07.160 JupyterHub log:166] {
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://MY_MOODLE_HOST/mod/lti/launch.php?id=2",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Origin": "http://MY_MOODLE_HOST",
      "Cache-Control": "max-age=0",
      "Content-Length": "1225",
      "Connection": "upgrade",
      "X-Scheme": "http",
      "X-Real-Ip": "180.217.109.173",
      "Host": "MY_JUPYTER_HOST"
    }
```

**Comment by xavierchan** [comment]
@owen198 I get the same trouble like you, do you have solve it ?

**Comment by consideRatio** [comment]
# Investigation time
The trail starts here!

https://github.com/jupyterhub/ltiauthenticator/blob/6d4db95289d58eaff51c494b08d416769dec0711/ltiauthenticator/__init__.py#L125-L141

It seems that `self.requests` isn't defined in the ltiauthenticator, so perhaps in the `Authenticator` base class. I looked there and conclude that it isn't defined in the base class either. But it should probably be `handler.request` instead.

But, what is a `handler`, and what is a `request` object?

From the Authenticator base class, [I learned about the `handler` parameter to the `authenticate` function](https://github.com/jupyterhub/jupyterhub/blob/abb93ad799865a4b27f677e126ab917241e1af72/jupyterhub/auth.py#L474-L500), it is a [tornado.web.RequestHandler](https://www.tornadoweb.org/en/stable/web.html#request-handlers), and that [`RequestHandler.request`](https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.request) is a [tornado.httputil.HTTPServerRequest](https://www.tornadoweb.org/en/stable/httputil.html#tornado.httputil.HTTPServerRequest) that indeed [have a `protocol` property](https://www.tornadoweb.org/en/stable/httputil.html#tornado.httputil.HTTPServerRequest.protocol)! The fix should be to make this `self.request` to `handler.request` simply!
