### ISSUE TITLE
Use usernames instead of user IDs

### ISSUE THREAD

**Issue by ghost** [jupyterhub/ltiauthenticator#30]
I'm currently using LTI authentication with Moodle. By default, the user IDs are used to create the JHub users. Is it possible to use the Moodle usernames (or first/last names) instead?

Help is appreciated. Thanks!

**Comment by cgawron** [comment]
I'm also trying to solve this ...

**Comment by BenGig** [comment]
Would be solved by PR #14, we would be very happy to get this feature, too.

**Comment by jgwerner** [comment]
Hi, @BenGig and @cgawron we opened #48 and would love your feedback if you have any. I added some unit tests and have tested with our LMS dev environment but it would be great if you could help validate this update too. 

As soon as it's approved by @yuvipanda and/or @consideRatio we will get this merged for you.

Thanks!
