### ISSUE TITLE
LTI operations

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [jupyterhub/ltiauthenticator#35]
Hi guys, I have implemented an LTI Tool that perfectly authenticates with JupyterHub. Looking at the this LTI authenticator there is no extra methods for the basic operations: **LTI Basic Outcomes Service** [https://www.imsglobal.org/specs/ltiv1p1/implementation-guide#toc-6](speficied here)

The LTI v1.1 docs say the endpoints and params to use, but the auth info should already be provided into the initial authentication process (this authenticator _should_ get it), and then use it to call with it.

for that there is the need of authentication, and because the _auth_ process validation is done in here I was wondering if you could help with this, with some feature, or even just some code snippets here that I can include myself into my custom code.

Thank you very much!

**Comment by jgwerner** [comment]
Hi @AdrianSanchezLopez do you still need help with this? If so may I suggest you start a thread (if you haven't done so) in [Jupyter's Community site](https://discourse.jupyter.org/)? This site gets a lot more traffic and these types of Q&A's are better suited for that site. Thanks!

**Comment by consideRatio** [comment]
I'll close this issue as there was no response.
