### ISSUE TITLE
Add an LTI 1.3 Authenticator

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/ltiauthenticator#38]
Currentl, we support an LTI 1.1 based Authenticator. LTI 1.3 is a significant improvement, and we should support that too. An additional authenticator here is probably the way to go

**Comment by yuvipanda** [comment]
Based on         https://twitter.com/illumidesknow/status/1357679777793126401, Illumidesk seems to have an implementation that would fit in nicely here.

**Comment by jgwerner** [comment]
@yuvipanda we will send a PR this week! We'd like to reorganize some things based on JupyterHub recommended patterns. It's a good excuse to clean up our code 👍

**Comment by yuvipanda** [comment]
@jgwerner yay! Looking forward to it.
