### ISSUE TITLE
Thank you @jgwerner - and an invite to be recognized as a project maintainer

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ltiauthenticator#45]
@jgwerner thank you for your care and effort put into this project! :heart: :tada:

I personally appreciate how you have worked to contribute to the long term maintenance of this project by adding test, helping with autoformatting practices, refactoring logic for readability etc. I love it!

Having discussed this with @yuvipanda, we would like to ask you: would you like to be recognized as an official maintainer of this project?

**Comment by jgwerner** [comment]
Hi @consideRatio sure, I could jump into the fold 😄 . I'll try to complete the LTI 1.3 PR (#39) this week.

**Comment by consideRatio** [comment]
Wieeee! :heart: thank you for your care and effort @jgwerner!
