### ISSUE TITLE
Add an LTI 1.1 Tool Provider XML endpoint

### ISSUE THREAD

**Issue by jgwerner** [jupyterhub/ltiauthenticator#49]
### Proposed change

Add a new LTI 1.1 handler to dynamically display the LTI 1.1 configuration XML.

### Alternative options

To add an LTI Link for a [Tool Consumer](https://www.imsglobal.org/specs/lti/xml) users have to manually include the LTI 1.1 settings values to the LMS' LTI 1.1 configuration page, manually create an XML based on the standard LTI 1.1 specification to paste it into the LMS configuration page, among others.

### Who would use this feature?

Any user that needs to quickly add the JupyterHub as a Tool Provider to a Tool Consumer (LMS).

### Suggest a solution

Create a handler and publish the correct XML with a web-accessible endpoint based on JupyterHub's URL, placements settings, etc.

**Comment by yuvipanda** [comment]
Would be awesome :)
