### ISSUE TITLE
Issues with LTI Canvas and Logins

### ISSUE THREAD

**Issue by whositwhatnow** [jupyterhub/ltiauthenticator#53]
We are testing a JH instance using LTI, we get it to successfully connect from Canvas to our JH instance, but the issue is it is not using the specific user ID we are requesting.

We do not want to use Canvas IDs we want to use a username instead.  We have the configuration attributes we want to use but it is not pulling those values and still giving us the canvas ID (not converting to the username).

jupyterhub                  1.4.1
jupyterhub-ltiauthenticator 1.0.0
jupyterhub-systemdspawner   0.15.0

#####################################################################
#####################################################################
c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers = {
       "KEY": "KEY"
}
c.LTIAuthenticator.username_key = 'lis_person_sourcedid'

**Comment by jgwerner** [comment]
Hi @whositwhatnow, thanks for the feedback.

I ran some tests and was able to change the `username_key` to another value from the launch request. To clarify the setup I opened #54 with an [example LTI 1.1 configuration setup and a brief README](https://github.com/jgwerner/ltiauthenticator/tree/docs/add-examples/examples) to help you replicate the tests.

**Comment by jgwerner** [comment]
@whositwhatnow it would be great if you could provide us with some feedback for the example provided in #54 - if it works we could close this issue, if not we will help you with further debugging.

If you still have issues, please provide:

- A copy of the log output (ensure it's in debug mode) from the JupyterHub authentication flow.
- A copy of your jupyterhub_config.py

**Comment by whositwhatnow** [comment]
So we noticed a difference with the PyPI version and the git branch version.  In order to get it to use the custom ID we had to modify 
/usr/local/lib/python3.6/site-packages/ltiauthenticator/__init__.py
line 159, 162

Looks like the pypi version is using LTI 1.0

**Comment by jgwerner** [comment]
Thanks @whositwhatnow - @consideRatio @yuvipanda perhaps we should cut a release for the current version with LT 1.1 and then another after completing the work for LTI 1.3?

**Comment by consideRatio** [comment]
Ah, so the `username_key` would solve this, but it is unreleased. I'll go ahead and close this, and note that version 1.1.0 will have the username_key configuration, see #60 for progress on that.
