### ISSUE TITLE
Create and publish documentation via Readthedocs

### ISSUE THREAD

**Issue by jgwerner** [jupyterhub/ltiauthenticator#55]
### Proposed change

Migrate most documentation from the included README to [Readthedocs](https://readthedocs.org/).

### Alternative options

Keep the existing README.md and add more content to that file.

### Who would use this feature?

Anyone that needs access to user guides, tutorials, dev setup instructions, etc.

**Comment by consideRatio** [comment]
1. Hosting on readthedocs sounds great.
   - [ ] Create a readthedocs project
   - [ ] Invite a few people to be owners of it
   - [ ] Enable PR previews
   - [ ] Create a badge in the README (like in jupyterhub/zero-to-jupyterhub-k8s)
   - [ ] Create a RTD configuration file (like in jupyterhub/zero-to-jupyterhub-k8s)
2. Let's use MyST based markdown - it has worked out great, making us benefit from familiarity of markdown while also getting the benefits that rST had. This setup can be mirrored from jupyterhub/zero-to-jupyterhub-k8s as well.
3. I really appreciate having a vision for the structure to aim for that is clearly defined, and diataxis.fr provides that. I suggest we attempt to follow such structure. The key work to do that would be to create the four main topics and organize content under it, not to adjust the content to be perfect within them during this migration from having content in the README.md file.
   - Watch this video to get introduced to the system https://www.youtube.com/watch?v=qC1OYK5oqDo

**Comment by jgwerner** [comment]
@consideRatio thanks for the checklist 👍
