### ISSUE TITLE
Add support the latest release of PyJWT

### ISSUE THREAD

**Issue by jgwerner** [jupyterhub/ltiauthenticator#76]
We currently have the PyJWT package (required for the current implementation of the LTI 1.3 Authenticator) to not install version 2+. We need to refactor the code to support the latest release of this package or replace it altogether.

**Comment by consideRatio** [comment]
Oh... We now require pyjwt>=2 in oauthenticator when used together with various identity providers: https://github.com/jupyterhub/oauthenticator/pull/506.

In the [JupyterHub helm chart's image](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.in), we install ltiauthenticator and oauthenticator, so this will causing some trouble now.

Can we make this package either compatible with pyjwt 2 alongside version 1, or make it require pyjwt 2+?

**Comment by consideRatio** [comment]
@jgwerner is this something you would be willing to help out with? I'm worried I can't test this properly if I attempt it, and that there will be a need for someone to verify things still function.
