### ISSUE TITLE
405 : Method Not Allowed

### ISSUE THREAD

**Issue by cequn** [jupyterhub/ltiauthenticator#8]
I follow the guide and try to make it work with open edx, but when i click the button, i got the error:
405 : Method Not Allowed

how to figure it out?

**Comment by cequn** [comment]
finally it works, but why i have to create a user "student"?

**Comment by consideRatio** [comment]
I'm looking through issues at the moment, quite new as a maintainer of this repo.

I'll go ahead and close this as the initial issue in title was resolved by what I assume to be a configuration change of how this python package was used. Feel free to open a new issue!
