### ISSUE TITLE
Urgent: cut a beta release to help test #91?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ltiauthenticator#92]
#91 adds supports, and even requires the library pyjwt 2+.

A breaking change, and also a change that I haven't tested as I'm not a user of this authenticator.

I want this done as quickly as possible, because:
1. its a security warning about pyjwt <2.4.0, fixed in 2.4.0
2. oauthenticator will require pyjwt >2 in its 15.0.0 release, while this now requires <2, making z2jh unable to have both ltiauthenticator and oauthenticator

Since I can't test this, I suggest we merge #91 and cut a beta release, then ask on discourse.jupyter.org for feedback. @jgwerner @yuvipanda, what do you think?

**Comment by yuvipanda** [comment]
I've a working instance with the LTIAuthenticator and am testing this there now.

**Comment by yuvipanda** [comment]
I tested and merged that PR!
